### ISSUE TITLE
Flip UndoList.new arguments? (to ease using it with the |> operator)

### ISSUE THREAD

**Issue by cbenz** [elm-community/elm-undo-redo#5]
I find myself doing this:

``` elm
newModel = model.present
  |> f x
  |> g
  |> (\newState -> UndoList.new newState model)
```

If we flip [`UndoList.new`](http://package.elm-lang.org/packages/elm-community/undo-redo/1.0.0/UndoList#new) arguments like:

``` diff
-new : state -> UndoList state -> UndoList state
+new : UndoList state -> state -> UndoList state
```

we'd be able to do:

``` elm
newModel = model.present
  |> f x
  |> g
  |> UndoList.new model
```

I know we can use [`flip`](http://package.elm-lang.org/packages/elm-lang/core/4.0.5/Basics#flip), so I don't know if my issue is relevant.

Thanks

**Comment by mgold** [comment]
Hmm. The current order follows "the data structure is always last", which is supposed to make this nice. Thinking about how you'd do this with `Dict`, instead of doing a `Dict.get`, chaining many functions, and then doing a `Dict.insert`, you'd use `[Dict.update](http://package.elm-lang.org/packages/elm-lang/core/4.0.5/Dict#update)`.

The name `update` is already used in this module, though it should probably be removed (see #4). So this would be a major release -- which I'm not opposed to doing, just doing quickly.

**Comment by cbenz** [comment]
Thanks for your reply. I totally understand "the data structure is always last". And that this my choice to use the pipe this way.

Feel free to close the issue.
